"use client";
import { useState } from "react";
import type { AppData, Food, Recipe } from "@/lib/app-types";
import { api } from "@/lib/client-api";
import { calculateFoodNutrition, calculateRecipeNutrition } from "@/lib/nutrition";
import type { RecordInput } from "@/lib/record-validation";

const blankFood = { name:"",servingAmount:100,servingUnit:"g",calories:0,protein:0,carbs:0,fat:0,favorite:false };
export function Library({ data, cloud, refresh, onChoose }: { data:AppData;cloud:boolean;refresh:()=>Promise<void>;onChoose:(input:RecordInput)=>void }) {
  const [food,setFood]=useState<Omit<Food,"id">&{id?:string}|null>(null);
  const [recipe,setRecipe]=useState<Omit<Recipe,"id">&{id?:string}|null>(null);
  const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [quantity,setQuantity]=useState<Record<string,number>>({}); const [filter,setFilter]=useState("");
  async function save(kind:"food"|"recipe", value:object&{id?:string}) { setBusy(true);setError("");try{await api("/api/library",value.id?"PUT":"POST",{kind,...value});await refresh();setFood(null);setRecipe(null);}catch(e){setError(e instanceof Error?e.message:"Error al guardar");}finally{setBusy(false);} }
  async function remove(kind:"food"|"recipe",id:string) {if(!confirm("¿Eliminar del catálogo? Los registros guardados se conservan."))return;try{await api("/api/library","DELETE",{kind,id});await refresh();}catch(e){setError(e instanceof Error?e.message:"Error al eliminar");}}
  function meal(name:string,quantity:number,unit:string,macros:{calories:number;protein:number;carbs:number;fat:number},source:"favorite"|"recipe") {onChoose({kind:"meal",timestamp:new Date().toISOString(),category:"Almuerzo",notes:"",items:[{name,quantity,unit,...macros,source,estimated:false}]});}
  return <div className="form"><h2>Alimentos y recetas</h2>{!cloud&&<p>El catálogo requiere iniciar sesión para guardar cambios.</p>}{error&&<p role="alert">{error}</p>}
    {food?<form onSubmit={e=>{e.preventDefault();void save("food",food);}}><h3>Valores por porción del alimento</h3>{(["name","servingAmount","servingUnit","calories","protein","carbs","fat"] as const).map(k=><label className="field" key={k}><span>{{name:"Nombre",servingAmount:"Cantidad de la porción base",servingUnit:"Unidad (g, ml, unidad, scoop)",calories:"Calorías",protein:"Proteína (g)",carbs:"Carbohidratos (g)",fat:"Grasas (g)"}[k]}</span><input required type={k==="name"||k==="servingUnit"?"text":"number"} min={k==="servingAmount"?"0.1":"0"} step="0.1" value={food[k]} onChange={e=>setFood({...food,[k]:k==="name"||k==="servingUnit"?e.target.value:Number(e.target.value)})}/></label>)}<label><input type="checkbox" checked={food.favorite} onChange={e=>setFood({...food,favorite:e.target.checked})}/> Favorito</label><button disabled={busy||!cloud} className="primary-button">Guardar alimento</button><button type="button" onClick={()=>setFood(null)}>Cancelar</button></form>:recipe?<form onSubmit={e=>{e.preventDefault();void save("recipe",recipe);}}><label className="field"><span>Nombre de la receta</span><input required value={recipe.name} onChange={e=>setRecipe({...recipe,name:e.target.value})}/></label><label className="field"><span>Descripción</span><input value={recipe.description??""} onChange={e=>setRecipe({...recipe,description:e.target.value})}/></label><label className="field"><span>Porciones resultantes</span><input type="number" required min="0.1" step="0.1" value={recipe.servings} onChange={e=>setRecipe({...recipe,servings:Number(e.target.value)})}/></label>{recipe.ingredients.map((i,index)=><fieldset className="editor-item" key={index}><label className="field"><span>Alimento</span><select required value={i.foodId} onChange={e=>{const f=data.foods?.find(f=>f.id===e.target.value);setRecipe({...recipe,ingredients:recipe.ingredients.map((v,j)=>j===index?{foodId:e.target.value,quantity:f?.servingAmount??100,unit:f?.servingUnit??"g"}:v)});}}><option value="">Seleccionar</option>{data.foods?.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label className="field"><span>Cantidad ({i.unit})</span><input type="number" min="0.1" step="0.1" required value={i.quantity} onChange={e=>setRecipe({...recipe,ingredients:recipe.ingredients.map((v,j)=>j===index?{...v,quantity:Number(e.target.value)}:v)})}/></label><button type="button" onClick={()=>setRecipe({...recipe,ingredients:recipe.ingredients.filter((_,j)=>j!==index)})}>Quitar</button></fieldset>)}<button type="button" onClick={()=>setRecipe({...recipe,ingredients:[...recipe.ingredients,{foodId:"",quantity:100,unit:"g"}]})}>+ Ingrediente</button><button disabled={busy||!cloud} className="primary-button">Guardar receta</button><button type="button" onClick={()=>setRecipe(null)}>Cancelar</button></form>:<>
    <div className="two"><button onClick={()=>setFood({...blankFood})}>Nuevo alimento</button><button onClick={()=>setRecipe({name:"",description:"",servings:1,ingredients:[]})}>Nueva receta</button></div><label className="field"><span>Buscar alimento</span><input value={filter} onChange={e=>setFilter(e.target.value)}/></label>
    {[...(data.foods??[])].sort((a,b)=>Number(b.favorite)-Number(a.favorite)).filter(f=>f.name.toLowerCase().includes(filter.toLowerCase())).map(f=><section className="editor-item" key={f.id}><h3>{f.favorite?"★ ":""}{f.name}</h3><p>{f.calories} kcal · {f.protein} g proteína por {f.servingAmount} {f.servingUnit}</p><label className="field"><span>Cantidad ({f.servingUnit})</span><input type="number" min="0.1" step="0.1" value={quantity[f.id]??f.servingAmount} onChange={e=>setQuantity({...quantity,[f.id]:Number(e.target.value)})}/></label><button disabled={(quantity[f.id]??f.servingAmount)<=0} onClick={()=>meal(f.name,quantity[f.id]??f.servingAmount,f.servingUnit,calculateFoodNutrition({...f,quantity:quantity[f.id]??f.servingAmount}),"favorite")}>Agregar al diario</button><button onClick={()=>setFood(f)}>Editar</button><button onClick={()=>void remove("food",f.id)}>Eliminar</button></section>)}
    <h3>Mis recetas</h3>{data.recipes?.map(r=>{const ingredients=r.ingredients.flatMap(i=>{const f=data.foods?.find(f=>f.id===i.foodId);return f?[{...f,quantity:i.quantity}]:[];});const macros=calculateRecipeNutrition(ingredients,r.servings);return <section key={r.id} className="editor-item"><h3>{r.name}</h3><p>Receta completa: {macros.total.calories} kcal · {macros.total.protein} g proteína</p><p>Por porción: {macros.perServing.calories} kcal · {macros.perServing.protein} g proteína</p><label className="field"><span>Porciones a registrar</span><input type="number" min="0.1" step="0.1" value={quantity[r.id]??1} onChange={e=>setQuantity({...quantity,[r.id]:Number(e.target.value)})}/></label><button disabled={(quantity[r.id]??1)<=0} onClick={()=>meal(r.name,quantity[r.id]??1,"porción",calculateFoodNutrition({...macros.perServing,servingAmount:1,quantity:quantity[r.id]??1}),"recipe")}>Agregar al diario</button><button onClick={()=>setRecipe(r)}>Editar receta</button><button onClick={()=>void remove("recipe",r.id)}>Eliminar</button></section>;})}</>}
  </div>;
}
