"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Camera, ChevronRight, Dumbbell, History, Home, Plus, Scale, Sparkles, TrendingDown, TrendingUp, UserRound, Utensils, X } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { ActivityEntry, AppData, MealCategory, MealEntry } from "@/lib/app-types";
import { createDemoData } from "@/lib/demo-data";
import { averageLoggedDays, movingAverage7, weightTrend } from "@/lib/reports";
import type { DetectedMeal } from "@/lib/validation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Progress as ProgressBar } from "@/components/ui/progress";
import { Switch } from "@/components/ui/switch";

type Tab = "today" | "history" | "progress" | "profile";
type Composer = "menu" | "meal" | "weight" | "activity" | "photo" | null;
const categories: MealCategory[] = ["Desayuno", "Almuerzo", "Merienda", "Cena", "Otros"];
const today = () => new Date().toISOString().slice(0, 10);
const fmt = new Intl.NumberFormat("es-AR");

export function NutritionApp({ initialData, cloud = false }: { initialData?: AppData; cloud?: boolean }) {
  const [tab, setTab] = useState<Tab>("today");
  const [composer, setComposer] = useState<Composer>(null);
  const [data, setData] = useState<AppData>(() => initialData ?? createDemoData());
  const [ready, setReady] = useState(false);

  useEffect(() => { const frame = requestAnimationFrame(() => { if (!cloud) { const saved = localStorage.getItem("andres-nutricion-v1"); if (saved) { try { setData(JSON.parse(saved)); } catch { /* conservar datos iniciales */ } } } setReady(true); }); return () => cancelAnimationFrame(frame); }, [cloud]);
  useEffect(() => { if (ready && !cloud) localStorage.setItem("andres-nutricion-v1", JSON.stringify(data)); }, [data, ready, cloud]);

  const addMeal = async (entry: Omit<MealEntry, "id" | "date" | "source">) => { let id=crypto.randomUUID(); if(cloud){const category={Desayuno:"BREAKFAST",Almuerzo:"LUNCH",Merienda:"SNACK",Cena:"DINNER",Otros:"OTHER"}[entry.category];const response=await fetch("/api/meals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...entry,category})});if(!response.ok)return;id=(await response.json()).id} setData((old) => ({ ...old, meals: [...old.meals, { ...entry, id, date: today(), source: "manual" }] })); setComposer(null); };
  const addWeight = async (weightKg: number) => { let id=crypto.randomUUID();if(cloud){const response=await fetch("/api/weights",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({weightKg})});if(!response.ok)return;id=(await response.json()).id}setData((old) => ({ ...old, weights: [...old.weights, { id, date: today(), weightKg }] })); setComposer(null); };
  const addActivity = async (entry: Omit<ActivityEntry, "id" | "date">) => { let id=crypto.randomUUID();if(cloud){const response=await fetch("/api/activities",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(entry)});if(!response.ok)return;id=(await response.json()).id}setData((old) => ({ ...old, activities: [...old.activities, { ...entry, id, date: today() }] })); setComposer(null); };
  const deleteMeal = async (id:string) => { if(cloud){const response=await fetch("/api/meals",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});if(!response.ok)return}setData((old)=>({...old,meals:old.meals.filter((m)=>m.id!==id)})); };
  const updateProfile = async (profile:AppData["profile"]) => { if(cloud){const response=await fetch("/api/profile",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(profile)});if(!response.ok)return}setData((old)=>({...old,profile})); };

  return <main className="app-frame">
    {tab === "today" && <TodayView data={data} onDelete={deleteMeal} />}
    {tab === "history" && <HistoryView data={data} />}
    {tab === "progress" && <ProgressView data={data} />}
    {tab === "profile" && <ProfileView data={data} onChange={updateProfile} />}
    <BottomNav tab={tab} setTab={setTab} onAdd={() => setComposer("menu")} />
    {composer && <ComposerSheet view={composer} setView={setComposer} onMeal={addMeal} onWeight={addWeight} onActivity={addActivity} />}
  </main>;
}

function Header({ eyebrow, title, subtitle }: { eyebrow?: string; title: string; subtitle?: string }) {
  return <header className="screen-header"><div>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{subtitle && <p className="subtle">{subtitle}</p>}</div><div className="avatar">AC</div></header>;
}

function TodayView({ data, onDelete }: { data: AppData; onDelete: (id: string) => void }) {
  const meals = data.meals.filter((meal) => meal.date === today());
  const totals = meals.reduce((a, m) => ({ calories: a.calories + m.calories, protein: a.protein + m.protein, carbs: a.carbs + m.carbs, fat: a.fat + m.fat }), { calories: 0, protein: 0, carbs: 0, fat: 0 });
  const dateLabel = new Intl.DateTimeFormat("es-AR", { weekday: "long", day: "numeric", month: "long" }).format(new Date());
  return <div className="screen"><Header eyebrow="ANDRÉS NUTRICIÓN" title="Hoy" subtitle={capitalize(dateLabel)} />
    <section className="hero-card"><div className="row top"><div><p className="hero-label">CALORÍAS</p><p className="hero-value">{fmt.format(totals.calories)} <span>/ {fmt.format(data.profile.calorieGoal)} kcal</span></p></div><Badge className="pill dark">{pct(totals.calories, data.profile.calorieGoal)}%</Badge></div><Bar value={totals.calories} goal={data.profile.calorieGoal} light /><p className="hero-note">{totals.calories <= data.profile.calorieGoal ? <>Te quedan aproximadamente <strong>{fmt.format(data.profile.calorieGoal - totals.calories)} kcal</strong></> : <>Superaste tu objetivo configurado en <strong>{fmt.format(totals.calories - data.profile.calorieGoal)} kcal</strong></>}</p></section>
    <div className="macro-grid"><Macro label="Proteína" value={totals.protein} goal={data.profile.proteinGoal} color="green" /><Macro label="Carbos" value={totals.carbs} goal={data.profile.carbGoal} color="amber" /><Macro label="Grasas" value={totals.fat} goal={data.profile.fatGoal} color="coral" /></div>
    <section className="section"><div className="section-heading"><div><p className="eyebrow">Tus comidas</p><h2>Registro de hoy</h2></div><span className="count">{meals.length} ítems</span></div>
      {categories.map((category) => { const items = meals.filter((m) => m.category === category); if (!items.length && !["Desayuno", "Almuerzo", "Cena"].includes(category)) return null; return <div className="meal-group" key={category}><div className="meal-title"><h3>{category}</h3><span>{items.reduce((s, i) => s + i.calories, 0)} kcal</span></div>{items.length ? items.map((item) => <article className="meal-item" key={item.id}><div className="food-icon"><Utensils size={18} /></div><div className="grow"><p className="item-name">{item.name}</p><p className="subtle">{item.quantity} {item.unit} · {item.protein} g proteína</p></div><button aria-label={`Eliminar ${item.name}`} className="delete" onClick={() => onDelete(item.id)}><X size={16} /></button></article>) : <p className="empty-inline">Todavía no registraste esta comida.</p>}</div>; })}
    </section>
  </div>;
}

function Macro({ label, value, goal, color }: { label: string; value: number; goal: number; color: string }) { return <Card className="macro-card"><p>{label}</p><strong>{Math.round(value)} <span>/ {Math.round(goal)} g</span></strong><Bar value={value} goal={goal} color={color} /></Card>; }
function Bar({ value, goal, light, color = "green" }: { value: number; goal: number; light?: boolean; color?: string }) { return <ProgressBar value={Math.min(100, pct(value, goal))} aria-label={`${Math.min(100, pct(value, goal))}% del objetivo`} className={`bar ${color} ${light ? "bar-light" : ""}`} />; }

function HistoryView({ data }: { data: AppData }) {
  const dates = useMemo(() => Array.from(new Set([...data.meals.map((x) => x.date), ...data.weights.map((x) => x.date), ...data.activities.map((x) => x.date)])).sort().reverse(), [data]);
  const [selected, setSelected] = useState(dates[0] ?? today());
  const meals = data.meals.filter((m) => m.date === selected); const weight = data.weights.find((w) => w.date === selected); const activities = data.activities.filter((a) => a.date === selected);
  return <div className="screen"><Header eyebrow="REGISTROS" title="Historial" subtitle="Cada día, con el contexto completo" /><section className="calendar-card"><div className="month-row"><button aria-label="Mes anterior">‹</button><strong>{new Intl.DateTimeFormat("es-AR", { month: "long", year: "numeric" }).format(new Date())}</strong><button aria-label="Mes siguiente">›</button></div><div className="date-strip">{dates.slice(0, 7).map((date) => <button key={date} onClick={() => setSelected(date)} className={selected === date ? "selected" : ""}><span>{new Intl.DateTimeFormat("es-AR", { weekday: "short" }).format(new Date(`${date}T12:00:00`)).slice(0, 2)}</span><strong>{date.slice(-2)}</strong><i /></button>)}</div></section>
    <section className="section"><div className="section-heading"><div><p className="eyebrow">Detalle diario</p><h2>{humanDate(selected)}</h2></div></div><div className="summary-grid"><Mini label="Calorías" value={`${meals.reduce((s, x) => s + x.calories, 0)} kcal`} /><Mini label="Proteína" value={`${meals.reduce((s, x) => s + x.protein, 0)} g`} /><Mini label="Peso" value={weight ? `${weight.weightKg} kg` : "Sin dato"} /><Mini label="Actividad" value={`${activities.reduce((s, x) => s + x.duration, 0)} min`} /></div>
      {!meals.length ? <Empty icon={<CalendarDays />} title="Sin alimentación registrada" body="Un día vacío no se cuenta como 0 kcal." /> : meals.map((meal) => <article className="list-row" key={meal.id}><div><strong>{meal.name}</strong><p>{meal.category} · {meal.protein} g proteína</p></div><b>{meal.calories} kcal</b></article>)}
      {activities.map((a) => <article className="list-row" key={a.id}><div><strong>{a.type}</strong><p>{a.detail || "Actividad registrada"}</p></div><b>{a.duration} min</b></article>)}
    </section>
  </div>;
}

function ProgressView({ data }: { data: AppData }) {
  const daily = Object.values(data.meals.reduce<Record<string, { date: string; calories: number; protein: number; carbs: number; fat: number }>>((acc, meal) => { acc[meal.date] ??= { date: meal.date.slice(5), calories: 0, protein: 0, carbs: 0, fat: 0 }; acc[meal.date].calories += meal.calories; acc[meal.date].protein += meal.protein; acc[meal.date].carbs += meal.carbs; acc[meal.date].fat += meal.fat; return acc; }, {})).sort((a,b) => a.date.localeCompare(b.date));
  const avg = averageLoggedDays(daily, 7); const trend = weightTrend(data.weights); const chartWeights = movingAverage7([...data.weights].sort((a,b) => a.date.localeCompare(b.date))).map((x) => ({ ...x, label: x.date.slice(5) }));
  return <div className="screen"><Header eyebrow="TENDENCIAS" title="Progreso" subtitle="Los datos, sin juicios" /><div className="filter-row"><button className="active">7 días</button><button>Mes</button><button>3 meses</button><button>Todo</button></div>
    <div className="progress-feature"><p>Peso actual</p><div className="big-stat">{trend?.end ?? "—"} <span>kg</span></div>{trend && <p className="trend"><TrendingDown size={16} /> {Math.abs(trend.change)} kg desde el inicio</p>}</div>
    <div className="summary-grid"><Mini label="Calorías promedio" value={avg.averages ? `${avg.averages.calories}` : "—"} suffix="kcal/día" /><Mini label="Proteína promedio" value={avg.averages ? `${avg.averages.protein}` : "—"} suffix="g/día" /><Mini label="Entrenamientos" value={`${data.activities.filter((x) => x.type === "Gym" || x.type === "CrossFit").length}`} suffix="sesiones" /><Mini label="Cobertura" value={`${avg.daysLogged} / ${avg.totalDays}`} suffix="días" /></div>
    <ChartCard title="Tendencia de peso" subtitle="El promedio móvil aparece con 7 registros"><ResponsiveContainer width="100%" height={190}><AreaChart data={chartWeights}><defs><linearGradient id="weight" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#0f766e" stopOpacity={.3}/><stop offset="95%" stopColor="#0f766e" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#e2e8f0" vertical={false}/><XAxis dataKey="label" tickLine={false} axisLine={false} fontSize={11}/><YAxis domain={["dataMin - 1", "dataMax + 1"]} hide/><Tooltip/><Area dataKey="weightKg" type="monotone" stroke="#0f766e" strokeWidth={3} fill="url(#weight)" /></AreaChart></ResponsiveContainer></ChartCard>
    <ChartCard title="Calorías registradas" subtitle={`${avg.daysLogged} de 7 días con alimentación`}><ResponsiveContainer width="100%" height={190}><AreaChart data={daily}><CartesianGrid stroke="#e2e8f0" vertical={false}/><XAxis dataKey="date" tickLine={false} axisLine={false} fontSize={11}/><YAxis hide/><Tooltip/><Area dataKey="calories" type="monotone" stroke="#84a91e" strokeWidth={3} fill="#d9f99d" /></AreaChart></ResponsiveContainer></ChartCard>
  </div>;
}

function ProfileView({ data, onChange }: { data: AppData; onChange: (profile: AppData["profile"]) => void }) {
  const [profile, setProfile] = useState(data.profile); const change = (key: keyof typeof profile, value: string | boolean) => setProfile((p) => ({ ...p, [key]: typeof p[key] === "number" ? Number(value) : value }));
  return <div className="screen"><Header eyebrow="TU CONFIGURACIÓN" title="Perfil" subtitle="Objetivos ajustables, historial preservado" /><section className="profile-card"><div className="profile-avatar">AC</div><div><h2>{profile.name}</h2><p>Objetivo: perder grasa manteniendo rendimiento</p></div></section>
    <form className="settings" onSubmit={(e) => { e.preventDefault(); onChange(profile); }}><h2>Datos personales</h2><Field label="Nombre"><input value={profile.name} onChange={(e) => change("name", e.target.value)} /></Field><div className="two"><Field label="Edad"><input type="number" value={profile.age} onChange={(e) => change("age", e.target.value)} /></Field><Field label="Altura"><div className="with-unit"><input type="number" value={profile.height} onChange={(e) => change("height", e.target.value)} /><span>cm</span></div></Field></div>
      <h2>Objetivo diario</h2><div className="two"><Field label="Calorías"><div className="with-unit"><input type="number" value={profile.calorieGoal} onChange={(e) => change("calorieGoal", e.target.value)} /><span>kcal</span></div></Field><Field label="Proteína"><div className="with-unit"><input type="number" value={profile.proteinGoal} onChange={(e) => change("proteinGoal", e.target.value)} /><span>g</span></div></Field><Field label="Grasas"><div className="with-unit"><input type="number" value={profile.fatGoal} onChange={(e) => change("fatGoal", e.target.value)} /><span>g</span></div></Field><Field label="Carbohidratos"><div className="with-unit"><input type="number" value={profile.carbGoal} onChange={(e) => change("carbGoal", e.target.value)} /><span>g</span></div></Field></div>
      <h2>Privacidad y región</h2><Field label="Zona horaria"><select value={profile.timezone} onChange={(e) => change("timezone", e.target.value)}><option>America/Argentina/San_Juan</option><option>America/Argentina/Buenos_Aires</option></select></Field><label className="toggle-row"><span><strong>Eliminar fotos después del análisis</strong><small>Las imágenes no se guardan permanentemente.</small></span><Switch checked={profile.deletePhotos} onCheckedChange={(checked) => change("deletePhotos", checked)} aria-label="Eliminar fotos después del análisis" /></label><Button className="primary-button" type="submit">Guardar cambios</Button></form>
  </div>;
}

function ComposerSheet({ view, setView, onMeal, onWeight, onActivity }: { view: Composer; setView: (v: Composer) => void; onMeal: (m: Omit<MealEntry,"id"|"date"|"source">) => void; onWeight: (w:number) => void; onActivity:(a: Omit<ActivityEntry,"id"|"date">)=>void }) {
  return <div className="sheet-backdrop" role="presentation" onMouseDown={(e) => { if (e.currentTarget === e.target) setView(null); }}><section className="sheet" role="dialog" aria-modal="true" aria-label="Agregar registro"><div className="sheet-handle" /><button className="close" onClick={() => setView(null)} aria-label="Cerrar"><X /></button>{view === "menu" && <AddMenu setView={setView} />}{view === "meal" && <MealForm onSave={onMeal} />}{view === "weight" && <WeightForm onSave={onWeight} />}{view === "activity" && <ActivityForm onSave={onActivity} />}{view === "photo" && <PhotoFlow setView={setView} />}</section></div>;
}

function AddMenu({ setView }: { setView:(v:Composer)=>void }) { const actions = [{ icon:<Camera/>, title:"Analizar comida con foto", sub:"Detectá y confirmá cada ingrediente", view:"photo" as const, featured:true },{ icon:<Utensils/>, title:"Agregar comida manual", sub:"Ingresá cantidades y macros", view:"meal" as const },{ icon:<Scale/>, title:"Registrar peso", sub:"Seguimos la tendencia, no un solo día", view:"weight" as const },{ icon:<Dumbbell/>, title:"Registrar actividad", sub:"Gym, CrossFit o caminata", view:"activity" as const }]; return <><div className="sheet-title"><p className="eyebrow">NUEVO REGISTRO</p><h2>¿Qué querés agregar?</h2></div><div className="action-list">{actions.map((a)=><button className={a.featured?"featured":""} key={a.title} onClick={()=>setView(a.view)}><span className="action-icon">{a.icon}</span><span><strong>{a.title}</strong><small>{a.sub}</small></span><ChevronRight/></button>)}</div></>; }

function MealForm({ onSave }: { onSave:(m:Omit<MealEntry,"id"|"date"|"source">)=>void }) { const [form,setForm]=useState({category:"Almuerzo" as MealCategory,name:"",quantity:100,unit:"g",calories:0,protein:0,carbs:0,fat:0}); const field=(key:keyof typeof form,value:string)=>setForm({...form,[key]:["name","unit","category"].includes(key)?value:Number(value)} as typeof form); return <form className="form" onSubmit={(e)=>{e.preventDefault();onSave(form)}}><div className="sheet-title"><p className="eyebrow">COMIDA MANUAL</p><h2>Agregar alimento</h2></div><Field label="Nombre"><input required autoFocus placeholder="Ej. pechuga de pollo" value={form.name} onChange={e=>field("name",e.target.value)}/></Field><div className="two"><Field label="Cantidad"><input required type="number" min="0.1" step="0.1" value={form.quantity} onChange={e=>field("quantity",e.target.value)}/></Field><Field label="Unidad"><select value={form.unit} onChange={e=>field("unit",e.target.value)}>{["g","ml","unidad","porción","scoop","cucharada","taza"].map(x=><option key={x}>{x}</option>)}</select></Field></div><Field label="Comida"><select value={form.category} onChange={e=>field("category",e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></Field><div className="two"><Field label="Calorías"><input type="number" min="0" value={form.calories} onChange={e=>field("calories",e.target.value)}/></Field><Field label="Proteína (g)"><input type="number" min="0" step="0.1" value={form.protein} onChange={e=>field("protein",e.target.value)}/></Field><Field label="Carbos (g)"><input type="number" min="0" step="0.1" value={form.carbs} onChange={e=>field("carbs",e.target.value)}/></Field><Field label="Grasas (g)"><input type="number" min="0" step="0.1" value={form.fat} onChange={e=>field("fat",e.target.value)}/></Field></div><Button className="primary-button" type="submit">Guardar comida</Button></form>; }
function WeightForm({ onSave }:{onSave:(w:number)=>void}) { const [weight,setWeight]=useState(91.4); return <form className="form" onSubmit={e=>{e.preventDefault();onSave(weight)}}><div className="sheet-title"><p className="eyebrow">PESO</p><h2>Registrar peso</h2><p className="subtle">Importa la tendencia, no la fluctuación de un día.</p></div><Field label="Peso actual"><div className="with-unit big-input"><input autoFocus type="number" min="30" max="300" step="0.1" value={weight} onChange={e=>setWeight(Number(e.target.value))}/><span>kg</span></div></Field><Button className="primary-button" type="submit">Guardar peso</Button></form>; }
function ActivityForm({onSave}:{onSave:(a:Omit<ActivityEntry,"id"|"date">)=>void}) { const [type,setType]=useState<ActivityEntry["type"]>("Gym"); const [duration,setDuration]=useState(60); const [detail,setDetail]=useState(""); return <form className="form" onSubmit={e=>{e.preventDefault();onSave({type,duration,detail})}}><div className="sheet-title"><p className="eyebrow">MOVIMIENTO</p><h2>Registrar actividad</h2></div><Field label="Tipo"><select value={type} onChange={e=>setType(e.target.value as ActivityEntry["type"])}>{["Gym","CrossFit","Caminata","Otro"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Duración"><div className="with-unit"><input type="number" min="1" value={duration} onChange={e=>setDuration(Number(e.target.value))}/><span>min</span></div></Field><Field label="Detalle opcional"><input placeholder="Ej. Día III o 4 km" value={detail} onChange={e=>setDetail(e.target.value)}/></Field><Button className="primary-button">Guardar actividad</Button></form>; }
function PhotoFlow({setView}:{setView:(v:Composer)=>void}) {
  const [file,setFile]=useState<File|null>(null); const [result,setResult]=useState<DetectedMeal|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  async function analyze(){ if(!file)return; setLoading(true); setError(""); const body=new FormData(); body.append("image",file); try{ const response=await fetch("/api/ai/food",{method:"POST",body}); const payload=await response.json(); if(!response.ok) throw new Error(payload.error||"No se pudo analizar la foto."); setResult(payload); }catch(e){setError(e instanceof Error?e.message:"No se pudo analizar la foto.");}finally{setLoading(false)} }
  return <div className="form"><div className="sheet-title"><p className="eyebrow">ANÁLISIS ASISTIDO</p><h2>{result?"Confirmá los ingredientes":"Fotografiá tu comida"}</h2><p className="subtle">La IA propone ingredientes y porciones. Vos confirmás todo antes de guardar.</p></div>{!result&&<><label className="upload"><Camera size={34}/><strong>{file?file.name:"Tomar o elegir una foto"}</strong><span>JPG, PNG o HEIC · máximo 8 MB</span><input type="file" accept="image/*" capture="environment" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><div className="notice"><Sparkles size={18}/><p>Una foto no permite conocer calorías exactas. Las cantidades siempre se muestran como estimaciones editables.</p></div>{error&&<p className="form-error" role="alert">{error}</p>}<Button className="primary-button" disabled={!file||loading} onClick={analyze}>{loading?"Analizando…":"Analizar y revisar"}</Button></>}{result&&<><div className="detected-list">{result.foods.map((food,index)=><label key={`${food.name}-${index}`}><input type="checkbox" defaultChecked/><span><strong>{food.name}</strong><small>{food.estimatedQuantity?`Cantidad estimada: ${food.estimatedQuantity} ${food.unit||"g"}`:"Cantidad por confirmar"}{food.preparation?` · ${food.preparation}`:""}</small></span></label>)}</div>{result.questions.map(q=><Field key={q.id} label={q.question}><select defaultValue=""><option value="" disabled>Seleccioná una opción</option>{q.options.map(option=><option key={option}>{option}</option>)}</select></Field>)}<p className="estimation-note">Las cantidades fueron estimadas a partir de la fotografía.</p><Button className="primary-button" onClick={()=>setView("meal")}>Confirmar y completar nutrición</Button></>}</div>;
}

function BottomNav({tab,setTab,onAdd}:{tab:Tab;setTab:(t:Tab)=>void;onAdd:()=>void}) { const items=[{id:"today" as const,label:"Hoy",icon:<Home/>},{id:"history" as const,label:"Historial",icon:<History/>},{id:"progress" as const,label:"Progreso",icon:<TrendingUp/>},{id:"profile" as const,label:"Perfil",icon:<UserRound/>}]; return <nav className="bottom-nav" aria-label="Navegación principal"><button className={tab===items[0].id?"active":""} onClick={()=>setTab(items[0].id)}>{items[0].icon}<span>{items[0].label}</span></button><button className={tab===items[1].id?"active":""} onClick={()=>setTab(items[1].id)}>{items[1].icon}<span>{items[1].label}</span></button><button className="add" aria-label="Agregar registro" onClick={onAdd}><Plus/></button><button className={tab===items[2].id?"active":""} onClick={()=>setTab(items[2].id)}>{items[2].icon}<span>{items[2].label}</span></button><button className={tab===items[3].id?"active":""} onClick={()=>setTab(items[3].id)}>{items[3].icon}<span>{items[3].label}</span></button></nav>; }
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Mini({label,value,suffix}:{label:string;value:string;suffix?:string}){return <Card className="mini"><p>{label}</p><strong>{value}</strong>{suffix&&<small>{suffix}</small>}</Card>}
function ChartCard({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <Card className="chart-card"><h3>{title}</h3><p>{subtitle}</p><div className="chart">{children}</div></Card>}
function Empty({icon,title,body}:{icon:React.ReactNode;title:string;body:string}){return <div className="empty">{icon}<strong>{title}</strong><p>{body}</p></div>}
const pct=(value:number,goal:number)=>goal?Math.round(value/goal*100):0;
const capitalize=(s:string)=>s.charAt(0).toUpperCase()+s.slice(1);
const humanDate=(iso:string)=>capitalize(new Intl.DateTimeFormat("es-AR",{weekday:"long",day:"numeric",month:"long"}).format(new Date(`${iso}T12:00:00`)));
