"use client";
import { useState } from "react";
import type { AppData } from "@/lib/app-types";
import { AccountControls } from "./account-controls";
import { HeightField } from "./height-field";
import { questionnaireSchema } from "@/lib/questionnaire";
export function ProfileView({ data, cloud, googleEnabled, onSave }: { data: AppData; cloud: boolean; googleEnabled: boolean; onSave: (profile: AppData["profile"]) => Promise<void> }) {
  const [profile,setProfile]=useState(data.profile); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const [height, setHeight] = useState(() => data.profile.height?.toString() ?? "");
  return <><form className="settings" onSubmit={async e=>{e.preventDefault();if(busy)return;setError("");const parsedHeight=questionnaireSchema.shape.height.safeParse(height.trim()===""?undefined:Number(height));if(!parsedHeight.success){setError("Ingresá tu altura en centímetros, entre 100 y 250 cm.");return;}setBusy(true);try{await onSave({...profile,height:parsedHeight.data});}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar.");}finally{setBusy(false);}}}><h2>Datos y objetivos</h2><HeightField value={height} onChange={setHeight} disabled={busy}/>{(Object.keys(labels) as (keyof typeof labels)[]).map(k=><label className="field" key={k}><span>{labels[k]}</span><input required type={typeof profile[k]==="number"?"number":"text"} step="any" value={profile[k]} onChange={e=>setProfile({...profile,[k]:typeof profile[k]==="number"?Number(e.target.value):e.target.value})}/></label>)}<div className="privacy-rule"><strong>Las fotos nunca se guardan</strong><p>Solo conservamos los datos nutricionales que confirmás.</p></div>{error&&<p role="alert">{error}</p>}<button disabled={busy} className="primary-button">{busy?"Guardando…":"Guardar cambios"}</button></form>{cloud&&<AccountControls googleEnabled={googleEnabled}/>}<section className="section"><h2>Mis datos</h2><button onClick={()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="nutricion-andres-datos.json";a.click();URL.revokeObjectURL(url);}}>Exportar mis registros</button></section></>;
}
const labels = { name:"Nombre",age:"Edad",timezone:"Zona horaria",calorieGoal:"Calorías",proteinGoal:"Proteína (g)",carbGoal:"Carbohidratos (g)",fatGoal:"Grasas (g)" };
