"use client";
import { useState } from "react";
import { Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import type { AppData } from "@/lib/app-types";
import { dateKeyInTimeZone } from "@/lib/reports";
import { periodSummary,shiftDate } from "@/lib/period-summary";
import { api } from "@/lib/client-api";
export function ReportsView({data,cloud}:{data:AppData;cloud:boolean}) {
  const [range,setRange]=useState(7);const [end,setEnd]=useState(dateKeyInTimeZone(new Date(),data.profile.timezone));const [analysis,setAnalysis]=useState("");const [busy,setBusy]=useState(false);
  const start=shiftDate(end,1-range);const report=periodSummary(data,start,end);const previous=periodSummary(data,shiftDate(start,-range),shiftDate(start,-1));
  return <><div className="filter-row">{[[7,"7 días"],[30,"30 días"],[90,"3 meses"]].map(([n,label])=><button key={n} className={range===n?"active":""} onClick={()=>{setRange(Number(n));setAnalysis("");}}>{label}</button>)}</div><label className="field"><span>Hasta el día</span><input type="date" value={end} onChange={e=>{setEnd(e.target.value);setAnalysis("");}}/></label><p>{start} — {end}</p><div className="summary-grid">{[["Calorías promedio",report.averageCalories??"Sin datos"],["Proteína promedio",report.averageProtein===null?"Sin datos":`${report.averageProtein} g`],["Cobertura",`${report.daysLogged} / ${report.totalDays} días`],["Entrenamientos",report.trainingSessions],["Minutos activos",report.activeMinutes],["Cambio de peso",report.weightChange===null?"Faltan registros":`${report.weightChange>0?"+":""}${report.weightChange} kg`]].map(([label,value])=><section className="mini" key={label}><p>{label}</p><strong>{value}</strong></section>)}</div><p>Período anterior: {previous.daysLogged}/{previous.totalDays} días registrados · {previous.averageCalories??"—"} kcal promedio · {previous.averageProtein??"—"} g proteína.</p><p className="subtle">Los promedios incluyen solo días con comidas registradas. La media móvil requiere siete días consecutivos con peso.</p>
  <section className="chart-card"><h3>Calorías y objetivos históricos</h3><ResponsiveContainer width="100%" height={220}><AreaChart data={report.daily.map(d=>({...d,calories:d.logged?d.calories:null}))}><CartesianGrid stroke="#dce3de"/><XAxis dataKey="date" hide/><YAxis/><Tooltip/><Area dataKey="calories" name="Calorías" stroke="#168063" fill="#c8ed68" connectNulls={false}/><Area dataKey="calorieGoal" name="Objetivo vigente" stroke="#e2a23b" fill="transparent"/></AreaChart></ResponsiveContainer></section>
  <section className="chart-card"><h3>Peso y promedio de 7 días</h3><ResponsiveContainer width="100%" height={220}><AreaChart data={report.weightChart}><XAxis dataKey="date" hide/><YAxis domain={["dataMin - 1","dataMax + 1"]}/><Tooltip/><Area dataKey="weightKg" name="Peso" stroke="#168063" fill="#dff1ad" connectNulls={false}/><Area dataKey="movingAverage" name="Media móvil" stroke="#d97706" fill="transparent" connectNulls={false}/></AreaChart></ResponsiveContainer></section>
  {cloud&&<section className="section"><button disabled={busy||!report.daysLogged} className="primary-button" onClick={async()=>{setBusy(true);try{const result=await api<{text:string}>("/api/ai/progress","POST",{start,end});setAnalysis(result.text);}catch(e){setAnalysis(e instanceof Error?e.message:"No se pudo analizar.");}finally{setBusy(false);}}}>{busy?"Analizando…":"Analizar este período con IA"}</button><p style={{whiteSpace:"pre-wrap"}} role="status">{analysis}</p></section>}</>;
}
